"""
Bundled SMS training corpus for MoMo Guard.
Labels: 1 = scam/smishing, 0 = legitimate.
Covers Kinyarwanda, English, French, and mixed-language messages.
Includes real MTN MoMo receipt patterns so the model learns that
shortcodes like *182* and *165* appear in legitimate messages too.
"""

TRAINING_DATA = [
    # ---- SCAMS (label=1) ----
    ("Kanda *182*1*1# kwakira 50,000 RWF byihuse mbere y'uko konti ihagarara.", 1),
    ("Emeza nonaha kugira ngo utazakura amafaranga yawe. *182*", 1),
    ("Muraho, konti yawe ya MoMo izafungwa. Kanda *182* uyifungure.", 1),
    ("Cliquez ici pour confirmer votre identite: bit.ly/mtn-rw", 1),
    ("Votre compte MoMo sera suspendu. Confirmez maintenant.", 1),
    ("URGENT: Your MoMo account has been blocked. Call 0789999999 immediately.", 1),
    ("You have won 500,000 RWF! Click bit.ly/claim to receive your prize.", 1),
    ("Watsindiye miliyoni imwe! Kanda *182* tombola amafaranga yawe.", 1),
    ("Dear customer, verify your account now or lose access. http://mtn-verify.ly", 1),
    ("Naje kugura konti yawe. Nkoherereza 50,000 RWF, yemeze nonaha.", 1),
    ("Murakoze, wohereje amafaranga. Kanda hano kwemeza: bit.ly/conf", 1),
    ("Amafaranga yawe azafungwa nibutaye kwemeza. *182*1*1#", 1),
    ("Bonjour, votre compte sera bloque dans 24h. Cliquez ici.", 1),
    ("Your bundle has expired. Dial *182* to reactivate now!", 1),
    ("Ubuhamya bwawe burakenewe. Kanda *182* ubu.", 1),
    ("Congratulations! You won 1,000,000 RWF. Send your PIN to claim.", 1),
    ("MTN: Your account is at risk. Verify immediately at mtn-secure.xyz", 1),
    ("Kanda kuri iyi link urebe amafaranga yawe: http://mtn.verify.ly", 1),
    ("Nimero yawe yatoranyijwe. Emeza nonaha kwakira 100,000 RWF.", 1),
    ("Urgent: dial *182*1*1# before your MoMo is suspended.", 1),
    ("Votre numero a ete selectionne. Confirmez votre PIN.", 1),
    ("Mwiriwe, nkeneye PIN yawe kugira ngo nkwereke amafaranga.", 1),
    ("Your MoMo PIN is required to complete this transaction. Reply now.", 1),
    ("Konti yawe ifite ikibazo. Kanda *182* uyikemure.", 1),
    ("Final notice: your account will be closed today. Click here.", 1),
    ("Urakoze cyane! Wabonye 200,000 RWF. Emeza kuyakira.", 1),
    ("Saa munani uraza kwakira amafaranga. Emeza mbere.", 1),
    ("We have detected fraud on your account. Call us now.", 1),
    ("Ntucikwe n'amafaranga. Kanda *182* ubu.", 1),
    ("Your MoMo balance is at risk. Act now: bit.ly/momo-safe", 1),
    ("Mwiriwe, wohereje 30,000 RWF ku kosa. Kanda uyisubize.", 1),
    ("Agent: send 5000 RWF to 0788XXXXX to unlock your account.", 1),
    ("Kanda 182 ubu cyangwa konti izafungwa.", 1),
    ("Cliquez sur ce lien pour debloquer votre compte MoMo.", 1),
    ("URGENT: You must re-verify your MoMo account within 1 hour.", 1),
    ("Wagurishije! Kanda hano kwakira amafaranga: bit.ly/sell", 1),
    ("Your MTN bundle has been reset. Verify your number to restore.", 1),
    ("Nimero yawe yahagaritswe. Kanda *182* uyifungure.", 1),
    ("Miliyoni 2 ziracyategereje! Emeza nonaha kuzikura.", 1),
    ("Dear user, your MoMo wallet requires immediate verification.", 1),
    ("Kanda *182*1*1# kwakira amafaranga y'ubufasha.", 1),
    ("Ntuzagire impungenge, kanda *182* gusa urebe.", 1),
    ("Votre solde MoMo est bloque. Confirmez votre identite ici.", 1),
    ("Send your PIN to 0788XXXXX to receive 50,000 RWF.", 1),
    ("Amafaranga 34,000 yazimiye kuri konti yawe. Kanda *182*", 1),
    ("MTN Rwanda: Your number won a bonus. Claim at bit.ly/bonus", 1),
    ("Kanda hano urebe ubutumwa buvuye kuri MTN: http://mtn-msg.ly", 1),
    ("Nimero yawe iri mu kaga. Kanda *182* nonaha.", 1),
    ("You have 24 hours to verify or your MoMo will be closed.", 1),
    ("Wemeze PIN yawe kuri iyi nimero: 0788XXXXX.", 1),
    ("Bonjour, cliquez ici pour recevoir votre remboursement.", 1),
    ("Urgent: dial *182* to unblock your MoMo account now.", 1),
    ("Konti yawe yagiye mu kaga. Kanda *182* uyikize.", 1),
    ("Your MoMo account has been compromised. Reset your PIN here.", 1),
    ("Kanda kuri link urebe amafaranga yawe: mtn.rw-verify.xyz", 1),
    ("Muraho, nshaka kuguha amafaranga. Ohereza PIN yawe.", 1),
    ("Final warning: activate your MoMo account or lose it.", 1),
    ("Byihuse! Wabonye 80,000 RWF. Emeza kuyakira.", 1),
    ("Cliquez ici: votre colis MoMo est en attente.", 1),
    ("Kanda *182* ubu kugira ngo utazakura amafaranga.", 1),

    # ---- SCAMS that misuse MTN shortcodes (paired examples) ----
    ("Dial *182* immediately to claim your 50,000 RWF prize.", 1),
    ("URGENT: Dial *182* to unlock your blocked MoMo account.", 1),
    ("Kanda *182* ubu kugira ngo utazakura amafaranga.", 1),
    ("Call *182* now or your MoMo will be suspended.", 1),
    ("Dial *165* to receive your bonus of 100,000 RWF today!", 1),
    ("Kanda *165* ubu kwakira amafaranga y'ubuntu.", 1),
    ("Send 5000 RWF to *182* to activate your reward.", 1),
    ("Dial *182*1*1# now to prevent account closure.", 1),

    # ---- LEGITIMATE (label=0) ----
    ("Wakiriye 12,000 RWF kuri konti yawe ya MoMo. Amafaranga asigaye: 34,500 RWF.", 0),
    ("Murakoze, wohereje 5,000 RWF kuri 0788XXXXX.", 0),
    ("Your MoMo balance is 12,500 RWF. Thank you for using MTN.", 0),
    ("Urakoze gukoresha MTN MoMo. Amafaranga yawe ni 8,200 RWF.", 0),
    ("You have successfully purchased a 1GB bundle. Enjoy!", 0),
    ("Waguze bundle ya 500MB. Urakoze.", 0),
    ("MTN MoMo: Your transaction of 2,000 RWF was successful.", 0),
    ("Amafaranga 3,000 yavuye kuri konti yawe. Asigaye: 15,000 RWF.", 0),
    ("Bonjour, votre paiement de 1,000 RWF a ete effectue.", 0),
    ("Your MoMo transfer to 0788XXXXX was successful.", 0),
    ("Urakoze kugura bundle. Izarangira kuwa 30.", 0),
    ("MTN: Your account is active. Balance: 5,400 RWF.", 0),
    ("Wakiriye 500 RWF kuri konti yawe.", 0),
    ("Successful: 10,000 RWF sent to 0788XXXXX.", 0),
    ("Ubuhamya: Waguriye umuntu 2,000 RWF.", 0),
    ("Your MoMo PIN was successfully changed.", 0),
    ("Murakoze, PIN yawe yahinduwe neza.", 0),
    ("You have received 25,000 RWF from 0788XXXXX.", 0),
    ("Wakiriye 8,500 RWF. Amafaranga asigaye: 22,000 RWF.", 0),
    ("MTN MoMo: Bundle yawe izarangira kuwa 15.", 0),
    ("Your cash withdrawal of 5,000 RWF was successful at agent 12345.", 0),
    ("Watoye 5,000 RWF kuri agent 12345. Urakoze.", 0),
    ("Votre solde MoMo est 14,200 RWF.", 0),
    ("Your bundle balance is 500MB. Valid until 30/12.", 0),
    ("Muraho, ubuhamya bwawe bwagenze neza.", 0),
    ("MTN: You have 1GB remaining in your bundle.", 0),
    ("Waguze bundle ya 1GB ku 500 RWF.", 0),
    ("Your transaction reference is TRX123456. Amount: 3,000 RWF.", 0),
    ("Urakoze gukoresha MTN MoMo. Transaction yawe yagenze neza.", 0),
    ("MTN MoMo: Your balance is 3,400 RWF. Valid on 31/12.", 0),
    ("Wakiriye 1,500 RWF kuva kuri 0788XXXXX.", 0),
    ("You have sent 2,500 RWF to 0788XXXXX successfully.", 0),
    ("Murakoze, ubutumwa bwawe bwakiriwe.", 0),
    ("MTN: Your MoMo account has been credited with 7,000 RWF.", 0),
    ("Washoboye kohereza 4,000 RWF. Amafaranga asigaye: 9,200 RWF.", 0),
    ("Votre transaction a ete effectuee avec succes.", 0),
    ("Your MoMo balance: 6,800 RWF. Thank you.", 0),
    ("Urakoze, waguriye umuntu 1,000 RWF.", 0),
    ("MTN MoMo: Dial *182# for balance. Your balance: 2,100 RWF.", 0),
    ("Wakiriye 500 RWF kuva kuri MTN.", 0),
    ("Your payment of 1,500 RWF to 0788XXXXX was successful.", 0),
    ("Murakoze gukoresha MTN. Ubuhamya bwawe bwakiriwe.", 0),
    ("MTN: Bundle yawe ya 1GB yaguze neza.", 0),
    ("Waguriye bundle. Amafaranga asigaye: 3,200 RWF.", 0),
    ("Your MoMo account balance is 12,000 RWF.", 0),
    ("Urakoze cyane, PIN yawe yahinduwe.", 0),
    ("MTN MoMo: Transaction successful. Reference: 182XXXX.", 0),
    ("Wakiriye 20,000 RWF kuva kuri 0788XXXXX.", 0),
    ("Your transfer of 500 RWF was successful.", 0),
    ("Murakoze, waguriye bundle ya 500MB.", 0),
    ("MTN: Your MoMo balance is 4,500 RWF. Valid until 30/12.", 0),
    ("Urakoze gukoresha MoMo. Transaction: 1,000 RWF.", 0),
    ("Your MoMo PIN was changed successfully.", 0),
    ("Wakiriye ubutumwa buvuye kuri MTN.", 0),
    ("MTN MoMo: You have 500MB remaining.", 0),
    ("Waguriye bundle ya 2GB ku 1,000 RWF.", 0),
    ("Your balance is 8,700 RWF. Transaction successful.", 0),
    ("Urakoze, ubuhamya bwawe bwagenze neza.", 0),
    ("MTN: Your account balance is 6,400 RWF.", 0),

    # ---- LEGIT MTN MoMo RECEIPT FORMATS (real-world) ----
    ("You have received 20000 RWF from Sonia KAMIKAZI (*********852) at 2026-09-15 13:59:37 . Balance:51437 RWF. FT Id: 30582458306.", 0),
    ("You have received 50000 RWF from John DOE (*********123) at 2026-09-15 14:00:00. Balance: 51437 RWF. FT Id: 30582458306.", 0),
    ("*165*S*20000 RWF transferred to Justin IMANIZABAYO (250780273068) at 2026-09-15 14:13:38 .Fee: 250RWF.Balance: 31187RWF.", 0),
    ("*165*S*5000 RWF transferred to Jane DOE (250788123456) at 2026-09-15 14:13:38. Fee: 100RWF. Balance: 31187RWF.", 0),
    ("Dial *182*1*3# and send money abroad *EN#", 0),
    ("Dial *182# to check your MoMo balance.", 0),
    ("Your MoMo balance is 51437 RWF. FT Id: 30582458306.", 0),
    ("You have received 20000 RWF. Your new balance is 51437 RWF. Transaction ID: 30582458306.", 0),
    ("*165*S* is used for MoMo transfers. Your transaction was successful.", 0),
    ("Fee: 250RWF. Balance: 31187RWF. Thank you for using MTN MoMo.", 0),
    ("FT Id: 30582458306. Amount: 20000 RWF. Balance: 51437 RWF.", 0),
    ("Your transfer of 20000 RWF to 250780273068 was successful. Fee: 250 RWF. Balance: 31187 RWF.", 0),
    ("You have sent 10000 RWF to Marie UMUTONI (250788111222). Fee: 100 RWF. Balance: 42187 RWF.", 0),
    ("Received 5000 RWF from +250788999888. Your balance is now 47187 RWF.", 0),
    ("Your MoMo statement for September is ready. Balance: 31187 RWF. Dial *182# for details.", 0),
    ("MTN MoMo: You have received 30000 RWF from Kigali Traders Ltd. Balance: 81187 RWF.", 0),
    ("Send money abroad with MTN MoMo. Dial *182*1*3# to start. Fee applies.", 0),
    ("*182*1*3# - International transfer service. Dial to begin. Standard rates apply.", 0),
    ("Transaction successful. FT Id: 30582458306. Amount: 20000 RWF. Fee: 250 RWF.", 0),
    ("Your MoMo account was credited with 20000 RWF on 2026-09-15. Balance: 51437 RWF.", 0),
]